version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=serene-spacedb
    ports:
      - 3307:3306

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
      
    environment:
      - MYSQLDB_HOST=backend
      - MYSQLDB_ROOT_PASSWORD=123456
      - MYSQLDB_DATABASE=mayba
      - MYSQLDB_LOCAL_PORT=3307
      - MYSQLDB_DOCKER_PORT=3306
      - JWT_SECRET=mysecretkey
